name: mindspore-lab repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch
    branches: [ master, main ]
  schedule:
    # Runs at 0,2,4,6...,22th hour every day (every 2 hours)
    - cron:  '0/5 * * * *'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
     - name: Mirror the github/mindspore-lab repos to openi.pcl.ac.cn/MindSpore.
       uses: jianyunchao/hub-mirror-action@master
       with:
         src: github/mindspore-lab
         dst: openi.pcl.ac.cn/MindSpore
         dst_key: ${{ secrets.OPENI_PRIVATE_KEY }}
         dst_token: ${{ secrets.OPENI_TOKEN }}
         account_type: org
         clone_style: ssh
         force_update: true
         static_list: "mindpet,mindrlhf,mindone,mindrec,mindcv,mindnlp,mindaudio,mindocr,mindyolo,mindface,mindrl"
         debug: true

     - name: Mirror the gitee/mindspore repos to openi.pcl.ac.cn/MindSpore.
       uses: jianyunchao/hub-mirror-action@master
       with:
         src: gitee/mindspore
         dst: openi.pcl.ac.cn/MindSpore
         dst_key: ${{ secrets.OPENI_PRIVATE_KEY }}
         dst_token:  ${{ secrets.OPENI_TOKEN }}
         account_type: org
         clone_style: ssh
         force_update: true
         static_list: 'mindformers,mindscience,mindquantum,graphlearning,mindpandas,hub,mindinsight,mindarmour,serving,federated,golden-stick,xai,ide-plugin'
         debug: true
