name: mindspore-lab repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch
    branches: [ master, main ]
  schedule:
    # Runs at 0,2,4,6...,22th hour every day (every 2 hours)
    - cron:  '0 */2 * * *'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Mirror the github/mindspore-lab org repos to gitee/mindspore-lab.
        uses: Yikun/hub-mirror-action@v1.0
        with:
          src: github/mindspore-lab
          dst: gitee/mindspore-lab
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          account_type: org
          clone_style: ssh
          force_update: true
          black_list: '-infrastructure,mindnlp-test'
          debug: true
